# Generated by Django 5.2.8 on 2026-01-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_variety',
            old_name='date_added',
            new_name='date_updated',
        ),
        migrations.AlterField(
            model_name='product_variety',
            name='type',
            field=models.CharField(choices=[('NEW', 'NEW ARRIVAL'), ('MNG', 'MANGA & COMICS'), ('MRC', 'MOST READ COMBOS'), ('SFI', 'SELF IMPROVEMENTS'), ('ROS', 'ROMANCE ON SALE'), ('HIN', 'HINDI BOOKS'), ('BSM', 'BUSINESS & STOCK-MARKET'), ('BST', 'BEST SELLERS')], max_length=4, unique=True),
        ),
    ]
