# Generated by Django 5.2.8 on 2026-01-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories', '0002_rename_date_added_product_variety_date_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_variety',
            old_name='date_updated',
            new_name='date_added',
        ),
    ]
