# Generated by Django 5.2.8 on 2025-12-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('category', models.CharField(choices=[('new_arrivals', 'New Arrivals'), ('manga_comics', 'Manga & Comics'), ('most_read_combos', 'Most Read Combos'), ('self_improvements', 'Self Improvements'), ('romance', 'Romance'), ('hindi', 'Hindi Books'), ('business_stock_market', 'Business & Stock Market'), ('best_sellers', 'Best Sellers')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
