# Generated by Django 5.2.8 on 2026-01-05 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('delivery_type', models.CharField(default='Standard (3-6 days)', max_length=100)),
                ('payment_method', models.CharField(default='card', max_length=50)),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('payu_txnid', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], db_index=True, default='pending_payment', max_length=20)),
                ('shiprocket_order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('shiprocket_status', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('awb_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('courier_name', models.CharField(blank=True, max_length=200, null=True)),
                ('label_url', models.URLField(blank=True, null=True)),
                ('tracking_data', models.JSONField(blank=True, default=dict)),
                ('shiprocket_shipment_created', models.BooleanField(db_index=True, default=False)),
                ('customer_notified', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='user_order_status_1dc5ca_idx'), models.Index(fields=['shiprocket_order_id'], name='user_order_shiproc_f3ba09_idx'), models.Index(fields=['payment_id'], name='user_order_payment_29d41a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('payment_id', ''), _negated=True), fields=('payment_id',), name='unique_payment_id'), models.UniqueConstraint(condition=models.Q(('shiprocket_order_id', ''), _negated=True), fields=('shiprocket_order_id',), name='unique_shiprocket_order'), models.UniqueConstraint(condition=models.Q(('payu_txnid', ''), _negated=True), fields=('payu_txnid',), name='unique_payu_txnid')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('book', 'Book'), ('addon', 'Addon')], default='book', max_length=20)),
                ('item_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('shiprocket_sku', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user.order')),
            ],
        ),
    ]
