# Generated by Django 5.2.8 on 2026-01-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_order_options_order_awb_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='courier_name',
            new_name='carrier_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shiprocket_order_id',
            new_name='carrier_order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='awb_number',
            new_name='shipping_status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shiprocket_status',
            new_name='tracking_number',
        ),
    ]
