# Generated by Django 5.2.8 on 2026-01-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_courier_name_order_carrier_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_status',
            new_name='awb_number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='carrier_name',
            new_name='courier_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='carrier_order_id',
            new_name='shiprocket_order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tracking_number',
            new_name='shiprocket_status',
        ),
    ]
