# Generated by Django 5.2.8 on 2026-01-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_order_shiprocket_status_order_tracking_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shiprocket_sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
