# Generated by Django 5.2.8 on 2026-01-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_order_shiprocket_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shiprocket_sku',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shiprocket_sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('book', 'Book'), ('addon', 'Addon')], default='book', max_length=20),
        ),
    ]
